CompileFlags:
  Add: [-std=c++20, -O3]
  Compiler: g++

Diagnostics:
  ClangTidy:
    Add: [modernize*, cppcoreguidelines*, bugprone*, clang-analyzer*, readability*, performance*, misc*]
    Remove: [modernize-use-trailing-return-type, readability-identifier-length]

